version: "3"

services:
  # backend
  nginx:
    build: ./backend/nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx:/etc/nginx/
    env_file:
      - ./backend/.env.backend
  app:
    build:
      context: ./backend/app/${BACKEND_ARCHITECTURE}
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080" # for uvicorn dev server
    volumes:
      - ./backend/app/${BACKEND_ARCHITECTURE}:/app
    env_file:
      - ./backend/.env.backend
    command: uvicorn main:app --host=0.0.0.0 --port=8080 --log-level=info --reload
  db:
    build:
      context: ./backend/db/mysql
      dockerfile: Dockerfile
    cap_add:
      - SYS_NICE
    expose:
      - "3306"
    volumes:
      - ./backend/db/mysql/volume:/var/lib/mysql
      - ./backend/db/mysql/conf.d:/etc/mysql/conf.d
      - ./backend/db/mysql/init.d:/docker-entrypoint-initdb.d
    env_file:
      - ./backend/.env.backend
  # frontend
  frontend:
    build:
      context: ./frontend/${FRONTEND_ARCHITECTURE}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/${FRONTEND_ARCHITECTURE}:/app
    env_file:
      - ./frontend/.env.frontend
    command: yarn start
    stdin_open: true
